### ISSUE TITLE
File upload/send error logging

### ISSUE THREAD

**Issue by mlenarsic** [OsiriX-Foundation/KheopsUI#90]
We've set up an instance of Kheops for testing purposes. During the import of some of our DICOM data we are encountering problems. To the POST /studies request we get responses with the status code of 409 and JSON bodies with various different response attributes. 

I understand that this is probably due to incompatibility of our DICOM files with the DICOMWeb standard, but understanding the sometimes vague responses can be quite difficult. Is there a way to access the logs on the server side to better understand the problems in our files?

**Comment by spalte** [comment]
The 409 code indicates that none of the instance could be stored [10.5.3.1 Status Codes](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_10.5.3.1).
You can find a description of the returned values in the [Store Instances Response Module Attributes](http://dicom.nema.org/medical/dicom/current/output/html/part18.html#chapter_I). We also use the 292 (0x124) Failure Reason for authorization failures.

Authorization failures on upload will typically happen if a series has already been uploaded, and belongs to another user. This is necessary since access control is handled at the series level. If a user has access to a series, we wouldn't want anyone else to be able to modify the series by uploaded additional instances that belong to the series. In practice we have found that this is not an issue. But since as developers where we are constantly uploading the same data, it is something to be aware of.

To dig in and see logs, the best places to look for hints for these sorts of issues are the Catalina logs (/usr/local/tomcat/logs) of the kheopsauthorization and kheopsdicomwebproxy containers. If it was the backing pacs that rejected the DICOM files, a good place to look is in (/opt/wildfly/standalone/log) of the pacsarc container.

**Comment by mlenarsic** [comment]
Thank you, by looking at the various logs we managed to get through all the issues with our DICOM files.
